from io import BytesIO

from fastapi import APIRouter
from starlette.responses import StreamingResponse

from dto.image import CreateImageRequest
from service.image_generator import create_image

image_router = APIRouter(prefix="/image", tags=["image"])


@image_router.post(
    "/create_image",
    responses={
        200: {
            "content": {"image/png": {}}
        }
    },

    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=StreamingResponse
)
async def create_image_by_theme(request: CreateImageRequest) -> StreamingResponse:
    image_bytes = BytesIO((await create_image(request.session_id, request.theme)).content)
    return StreamingResponse(
        content=image_bytes,
        media_type="image/png"
    )
